name: Despliegue Heroku Main
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2

    - name: Configuraci√≥n de entorno
      uses: actions/setup-node@v2
      with:
        node-version: '14.20'

    - name: Limpiear Node Modules
      run: rm -rf node_modules

    - name: Limpiar package-lock
      run: rm -f package-lock.json

    - name: Instalar dependencias
      run: npm i --force
      env:
          environment: production
